# Generated by Django 6.1.1 on 2026-10-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('max_participants', models.PositiveIntegerField()),
                ('booked_places', models.PositiveIntegerField(default=0)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_classes', to='gym.trainer')),
            ],
        ),
    ]
